scr_initenemy();
idlespr = spr_crackerkicker_walk;
stunfallspr = spr_crackerkicker_stunned;
walkspr = spr_crackerkicker_walk;
stunspr = spr_crackerkicker_stunned;
grabbedspr = spr_crackerkicker_stunned;
scaredspr = spr_crackerkicker_stunned;
spr_dead = spr_crackerkicker_dead;
sprite_index = walkspr;
sugary = true;
kickbuffer = 0;
