scr_initenemy();
stunfallspr = spr_smoreknight_stun;
walkspr = spr_smoreknight_walk;
scaredspr = spr_smoreknight_scared;
idlespr = spr_smoreknight_idle;
spr_dead = spr_smoreknight_dead;
spr_palette = spr_smoreknight_palette;
usepalette = true;
sprite_index = walkspr;
sugary = true;
